import { Pool, RowDataPacket } from 'mysql2/promise';
import fs from 'fs-extra';
import path from 'path';
import { getDbPool } from '../common/db';
import { logger, getMockFilePath } from '../common/logger';
import { config } from '../common/config';

// Dynamically construct the import path for frontend types
// This assumes that this script is run from the root of the bjt-data-sync project.
const typesPath = path.join(config.frontendMockDir, config.frontendTypesDirRelativeToMocks, 'consumables');
// Note: Adjust 'consumables' if your type file has a different name or path structure.
// We are trying to achieve an import like: import { ConsumableProduct } from '../../../../frontend/src/types/consumables';
// The exact relative path will depend on the final location of the generated mock files.

// Placeholder for actual type import - this will likely cause a TS error until the path is perfect
// and the build process can resolve it. For now, we define a local approximation.
// import { ConsumableProduct, ConsumableSpecification, ConsumablePriceTier, ConsumableInventory } from typesPath;

// Local approximation of frontend types (replace with actual import when pathing is resolved)
export interface ConsumableSpecification {
  label: string;
  value_metric: string;
  value_imperial: string;
}

export interface ConsumablePriceTier {
  min_quantity: number;
  max_quantity?: number;
  price_per_unit: number;
  currency: string;
}

export interface ConsumableInventory {
  region: string;
  stock_level: number;
  unit?: string; // e.g., "rolls", "pieces"
  status?: 'in_stock' | 'low_stock' | 'out_of_stock';
}

export interface ConsumableProduct {
  id: string; // Mock ID like "CONS001"
  product_id: string; // Typically part_number from DB
  name: string;
  code: string; // part_number from DB
  image_url: string;
  product_line_id?: number | string;
  model?: string;
  brand?: string;
  specifications: ConsumableSpecification[];
  compatibleModels: string[];
  pricingTiers: { [region: string]: ConsumablePriceTier[] };
  inventoryByRegion: ConsumableInventory[];
  description?: string;
  category?: string;
  more_info_fields?: { label: string; value: string }[];
}
// End of local type approximation

const MOCK_FILE_NAME = 'consumables.mocks.ts';

/**
 * Generates the TypeScript mock file content for consumables.
 * @param consumables - Array of ConsumableProduct data.
 * @returns string - The TypeScript file content.
 */
function generateMockFileContent(consumables: ConsumableProduct[]): string {
  // Construct the import path for ConsumableProduct from the perspective of the generated mock file
  // Example: if mocks are in frontend/src/services/mocks/ and types are in frontend/src/types/
  // the relative path from the mock file to the types directory is '../../types'
  const relativeTypesPath = config.frontendTypesDirRelativeToMocks.replace(/\\/g, '/');

  return `// Generated by bjt-data-sync script
// Do not edit manually

import { ConsumableProduct } from '${relativeTypesPath}/consumables';

export const mockConsumables: ConsumableProduct[] = ${JSON.stringify(consumables, null, 2)};
`;
}

/**
 * Fetches consumables data from the database and generates a mock file.
 */
export async function generateConsumablesMockFile(): Promise<void> {
  const pool: Pool = getDbPool();
  let allConsumablesData: ConsumableProduct[] = [];

  try {
    logger.info('Fetching consumables from database...');
    const [consumablesRows] = await pool.query<RowDataPacket[]>(
      'SELECT * FROM wp_bjt_consumables WHERE status = \'publish\' ORDER BY id ASC'
    );

    if (!consumablesRows || consumablesRows.length === 0) {
      logger.warn('No consumables found in the database.');
      // Write an empty array if no data
      const mockFilePath = getMockFilePath(MOCK_FILE_NAME);
      const fileContent = generateMockFileContent([]);
      await fs.writeFile(mockFilePath, fileContent);
      logger.info(`Empty consumables mock file generated at ${mockFilePath}`);
      return;
    }

    logger.info(`Fetched ${consumablesRows.length} consumable base entries.`);

    for (const consumableRow of consumablesRows) {
      const consumableId = consumableRow.id;
      const partNumber = consumableRow.part_number;

      // 1. Fetch Prices for this consumable
      const [priceRows] = await pool.query<RowDataPacket[]>(
        'SELECT * FROM wp_bjt_prices WHERE target_type = ? AND target_id = ? AND status = \'active\' ORDER BY region, min_quantity ASC',
        ['consumable', consumableId]
      );
      const pricingTiers: { [region: string]: ConsumablePriceTier[] } = {};
      priceRows.forEach(p => {
        if (!pricingTiers[p.region]) {
          pricingTiers[p.region] = [];
        }
        pricingTiers[p.region].push({
          min_quantity: p.min_quantity,
          max_quantity: p.max_quantity || undefined, // Handle NULL for open-ended max
          price_per_unit: parseFloat(p.base_price),
          currency: p.currency,
        });
      });

      // 2. Fetch Inventory for this consumable
      const [inventoryRows] = await pool.query<RowDataPacket[]>(
        'SELECT region, SUM(quantity) as total_stock FROM wp_bjt_inventory WHERE target_type = ? AND target_id = ? AND status = \'active\' GROUP BY region',
        ['consumable', consumableId]
      );
      const inventoryByRegion: ConsumableInventory[] = inventoryRows.map(inv => ({
        region: inv.region,
        stock_level: parseInt(inv.total_stock, 10),
        // unit and status can be enhanced later
      }));

      // 3. Fetch Compatibility for this consumable (using part_number)
      const [compatibilityRows] = await pool.query<RowDataPacket[]>(
        'SELECT host_model FROM wp_bjt_consumable_compatibility WHERE consumable_part_number = ? AND status = \'publish\'',
        [partNumber]
      );
      const compatibleModels: string[] = compatibilityRows.map(cr => cr.host_model);

      // 4. Construct Specifications (example structure, needs detailed mapping)
      const specifications: ConsumableSpecification[] = [];
      if (consumableRow.material) {
        specifications.push({ label: 'Material', value_metric: consumableRow.material, value_imperial: consumableRow.material });
      }
      if (consumableRow.thickness_met) {
        specifications.push({ label: 'Thickness', value_metric: `${consumableRow.thickness_met} um`, value_imperial: `${consumableRow.thickness_imp} mil` });
      }
      if (consumableRow.width_met) {
        specifications.push({ label: 'Width', value_metric: `${consumableRow.width_met} cm`, value_imperial: `${consumableRow.width_imp} inch` });
      }
      if (consumableRow.length_met) { // Assuming total_length_met for roll length
        specifications.push({ label: 'Length', value_metric: `${consumableRow.total_length_met || consumableRow.length_met} m`, value_imperial: `${consumableRow.total_length_imp || consumableRow.length_imp} ft` });
      }
       if (consumableRow.spec) {
        specifications.push({ label: 'Spec', value_metric: consumableRow.spec, value_imperial: consumableRow.spec_imperial || consumableRow.spec });
      }

      // 5. Create the ConsumableProduct object
      const consumableProduct: ConsumableProduct = {
        id: `CONS-${String(consumableRow.id).padStart(4, '0')}`, // Mock ID e.g., CONS-0001
        product_id: partNumber,
        code: partNumber,
        name: `${consumableRow.model || 'Consumable'} ${partNumber}`, // Basic name, can be improved
        image_url: consumableRow.image_url ? `${config.assetsBasePath}${consumableRow.image_url}` : '',
        product_line_id: consumableRow.product_line_id,
        model: consumableRow.model,
        brand: consumableRow.brand,
        description: consumableRow.description_zh || consumableRow.description_en || '', // Assuming description fields exist
        category: consumableRow.bag_type || consumableRow.material, // Example category derivation
        specifications,
        compatibleModels,
        pricingTiers,
        inventoryByRegion,
        more_info_fields: consumableRow.package_type ? [{label: 'Packaging', value: consumableRow.package_type}] : []
      };
      allConsumablesData.push(consumableProduct);
    }

    const mockFilePath = getMockFilePath(MOCK_FILE_NAME);
    const fileContent = generateMockFileContent(allConsumablesData);
    await fs.writeFile(mockFilePath, fileContent);

    logger.info(`Successfully generated consumables mock file: ${mockFilePath}`);

  } catch (error) {
    logger.error('Error generating consumables mock file:', error);
    throw error; // Re-throw to be caught by main script
  }
} 